### ISSUE TITLE
Error running LOGO

### ISSUE THREAD

**Issue by shhuang1** [menzel/nopeak#3]
I encountered the following error when trying to create sequence logos:
```
$ java -jar NoPeak-1.0-SNAPSHOT.jar LOGO --signal <signal_csv> -f 200 --strict
Significant motifs:
Motif:  NNNNNNNNGGATTCTCNNNNNNNN
K-mers count:   22
Exception in thread "main" java.lang.SecurityException: Prohibited package name: java.logo
        at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:898)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1014)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at main.Guesser.lambda$new$4(Guesser.java:68)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at main.Guesser.<init>(Guesser.java:62)
        at main.LogoHelper.logo(LogoHelper.java:55)
        at main.Main.main(Main.java:104)

```

Seems to be due to the package definition line in logo/Logo.java:
```
package java.logo;
```
Probably can be fixed by changing to 
```
package logo;
```

Thanks a lot!

**Comment by menzel** [comment]
Thanks for your notice. That somehow slip through when I changed the package structure a few weeks ago.

New code and new binary are online.

**Comment by shhuang1** [comment]
Thank you for the quick action!  I tried the new binary and still got the same error.  Is it possible that the change wasn't incorporated during compiling?

**Comment by menzel** [comment]
You are right, sorry I didn't test it. There were three other classes referring to java.logo instead of logo.
Somehow my IDE and Maven didn't check during compilation, today it did.

New code and tested binary are online.

**Comment by shhuang1** [comment]
This is working now.  Thanks a lot!
